[package]
org = "admin"
name = "ballerina_db_setup"
version = "0.1.0"
distribution = "2201.3.2"

[build-options]
observabilityIncluded = true
cloud="k8s"

[[dependency]]
org = "ballerina"
name = "cloud"
version = "2.5.1"
repository = "local"
