[package]
org = "com_comparision"
name = "social_media"
version = "0.0.1"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true
cloud="k8s"

# [[platform.java11.dependency]]
# artifactId = "h2"
# version = "2.0.206"
# groupId = "com.h2database"

[[dependency]]
org = "ballerina"
name = "cloud"
version = "2.5.1"
repository = "local"
