moderate = true
enableSmsNotification = false
natsUrl = "nats://localhost:4222"
stsHost = "sts-service-svc"
sentimentHost = "sentiment-api"

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
samplerParam=1.0
